### PR TITLE
Issue38

### PR DESCRIPTION
**Pull request by saschaschefenacker**
Initial PR for https://github.com/JanLahmann/RasQberry-Two/issues/38

I added a directory "examples" - not sure if that is the preferred place.

Final test still ongoing, so do not merge yet.
Just opening the PR to have it accessible for others.

### CODE REVIEW

**Comment by saschaschefenacker** [comment]
Would cover Issue https://github.com/JanLahmann/RasQberry-Two/issues/38 and https://github.com/JanLahmann/RasQberry-Two/issues/40

**Comment by saschaschefenacker** [comment]
Tested from me and Luka, seems to be good for a first merge.
SPI activation is covered from Gaia

**Comment by JanLahmann** [comment]
Could we use the default venv ("RQB2") instead of a new venv?
Would be good, as the default venv includes Qiskit, etc.

**Comment by saschaschefenacker** [comment]
accoring to https://docs.python.org/3/library/venv.html
the venv command just needs the folder to place it - I could easy adjust the script to not use ".venv" in the current directory.

adjusting to
"/home/pi/RasQberry-Two/venv/RQB2"

**Comment by gbanchelli** [comment]
> accoring to https://docs.python.org/3/library/venv.html the venv command just needs the folder to place it - I could easy adjust the script to not use ".venv" in the current directory.
> 
> adjusting to "/home/pi/RasQberry-Two/venv/RQB2"

Just a quick comment - that would be our $FIRST_USER_NAME's home directory rather than pi's.

**Comment by saschaschefenacker** [comment]
@JanLahmann - I see in the README that the username "pi" is used.
https://github.com/JanLahmann/RasQberry-Two/blob/main/README.md?plain=1#L40

But in the same README for qskit we work with variables:
https://github.com/JanLahmann/RasQberry-Two/blob/main/README.md?plain=1#L36

Do we want to stick to "pi" as user everywhere - to be consistent.
Or change to a variables ($HOME/$REPO/venv)?

The code change is easy, when we know the target

**Comment by rishimathur14** [comment]
ideally we support any user but default user is rasqberry so when you logging with ssh its already set virtual env with the username you have set so should ideally work with any users

**Comment by JanLahmann** [comment]
so shall we assume that the "default venv" is already activated?
That is true for our base image, and using the default user "raspberry".
(the README.md is outdated, unfortunately.)

**Comment by rishimathur14** [comment]
Jan for non interactive yes we need to fix for interactive. I will take
this up

**Comment by Luka-D** [comment]
Should the folder be named "demos" instead of "examples"?

**Comment by JanLahmann** [comment]
@Luka-D as this is just displaying text not he LEDs, but is not a quantum-related demo, "examples" is good. 
But you are right, we should also have a folder "demos" with quantum computing related demos.

**Comment by JanLahmann** [comment]
@saschaschefenacker shall we merge this PR?

**Comment by saschaschefenacker** [comment]
I think "yes" - technically it is working.
We may adjust the user-path in a later update (if required)

**Review by JanLahmann — APPROVED** [review]

**Pull request merged**
